# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 830)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.plotAS = PlotWidget(self.centralwidget)
        self.plotAS.setGeometry(QtCore.QRect(9, 119, 781, 111))
        self.plotAS.setAutoFillBackground(True)
        self.plotAS.setObjectName("plotAS")
        self.cbPorts = QtWidgets.QComboBox(self.centralwidget)
        self.cbPorts.setGeometry(QtCore.QRect(80, 20, 101, 31))
        self.cbPorts.setObjectName("cbPorts")
        self.lblLed = QtWidgets.QLabel(self.centralwidget)
        self.lblLed.setGeometry(QtCore.QRect(20, 15, 41, 41))
        self.lblLed.setText("")
        self.lblLed.setPixmap(QtGui.QPixmap(":/leds/red"))
        self.lblLed.setScaledContents(True)
        self.lblLed.setObjectName("lblLed")
        self.btnConnect = QtWidgets.QPushButton(self.centralwidget)
        self.btnConnect.setGeometry(QtCore.QRect(190, 20, 31, 31))
        self.btnConnect.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/button/close"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnConnect.setIcon(icon)
        self.btnConnect.setIconSize(QtCore.QSize(24, 24))
        self.btnConnect.setObjectName("btnConnect")
        self.btnUpdate = QtWidgets.QPushButton(self.centralwidget)
        self.btnUpdate.setGeometry(QtCore.QRect(230, 20, 31, 28))
        self.btnUpdate.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/button/update"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnUpdate.setIcon(icon1)
        self.btnUpdate.setIconSize(QtCore.QSize(24, 24))
        self.btnUpdate.setObjectName("btnUpdate")
        self.lblMessage = QtWidgets.QLabel(self.centralwidget)
        self.lblMessage.setGeometry(QtCore.QRect(20, 70, 761, 41))
        self.lblMessage.setFrameShape(QtWidgets.QFrame.Box)
        self.lblMessage.setText("")
        self.lblMessage.setAlignment(QtCore.Qt.AlignCenter)
        self.lblMessage.setObjectName("lblMessage")
        self.plotPS = PlotWidget(self.centralwidget)
        self.plotPS.setGeometry(QtCore.QRect(10, 250, 781, 111))
        self.plotPS.setAutoFillBackground(True)
        self.plotPS.setObjectName("plotPS")
        self.barGraphTV = GraphicsLayoutWidget(self.centralwidget)
        self.barGraphTV.setGeometry(QtCore.QRect(10, 380, 181, 141))
        self.barGraphTV.setAutoFillBackground(True)
        self.barGraphTV.setObjectName("barGraphTV")
        self.barGraphPX = QtWidgets.QWidget(self.centralwidget)
        self.barGraphPX.setGeometry(QtCore.QRect(400, 380, 181, 141))
        self.barGraphPX.setAutoFillBackground(True)
        self.barGraphPX.setObjectName("barGraphPX")
        self.pot1 = QtWidgets.QDial(self.centralwidget)
        self.pot1.setGeometry(QtCore.QRect(100, 620, 91, 101))
        self.pot1.setObjectName("pot1")
        self.lblMessage_2 = QtWidgets.QLabel(self.centralwidget)
        self.lblMessage_2.setGeometry(QtCore.QRect(250, 380, 111, 41))
        self.lblMessage_2.setFrameShape(QtWidgets.QFrame.Box)
        self.lblMessage_2.setText("")
        self.lblMessage_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lblMessage_2.setObjectName("lblMessage_2")
        self.pot2 = QtWidgets.QDial(self.centralwidget)
        self.pot2.setGeometry(QtCore.QRect(240, 620, 91, 101))
        self.pot2.setObjectName("pot2")
        self.pot3 = QtWidgets.QDial(self.centralwidget)
        self.pot3.setGeometry(QtCore.QRect(380, 620, 91, 101))
        self.pot3.setObjectName("pot3")
        self.pot4 = QtWidgets.QDial(self.centralwidget)
        self.pot4.setGeometry(QtCore.QRect(520, 620, 91, 101))
        self.pot4.setObjectName("pot4")
        self.lblMessage_3 = QtWidgets.QLabel(self.centralwidget)
        self.lblMessage_3.setGeometry(QtCore.QRect(100, 540, 91, 41))
        self.lblMessage_3.setFrameShape(QtWidgets.QFrame.Box)
        self.lblMessage_3.setText("")
        self.lblMessage_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lblMessage_3.setObjectName("lblMessage_3")
        self.lblMessage_4 = QtWidgets.QLabel(self.centralwidget)
        self.lblMessage_4.setGeometry(QtCore.QRect(240, 540, 91, 41))
        self.lblMessage_4.setFrameShape(QtWidgets.QFrame.Box)
        self.lblMessage_4.setText("")
        self.lblMessage_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lblMessage_4.setObjectName("lblMessage_4")
        self.lblMessage_5 = QtWidgets.QLabel(self.centralwidget)
        self.lblMessage_5.setGeometry(QtCore.QRect(380, 540, 91, 41))
        self.lblMessage_5.setFrameShape(QtWidgets.QFrame.Box)
        self.lblMessage_5.setText("")
        self.lblMessage_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lblMessage_5.setObjectName("lblMessage_5")
        self.lblMessage_6 = QtWidgets.QLabel(self.centralwidget)
        self.lblMessage_6.setGeometry(QtCore.QRect(520, 540, 91, 41))
        self.lblMessage_6.setFrameShape(QtWidgets.QFrame.Box)
        self.lblMessage_6.setText("")
        self.lblMessage_6.setAlignment(QtCore.Qt.AlignCenter)
        self.lblMessage_6.setObjectName("lblMessage_6")
        self.txtFile = QtWidgets.QLineEdit(self.centralwidget)
        self.txtFile.setGeometry(QtCore.QRect(440, 20, 261, 31))
        self.txtFile.setObjectName("txtFile")
        self.btnOpenFile = QtWidgets.QPushButton(self.centralwidget)
        self.btnOpenFile.setGeometry(QtCore.QRect(710, 20, 31, 28))
        self.btnOpenFile.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/button/file"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnOpenFile.setIcon(icon2)
        self.btnOpenFile.setIconSize(QtCore.QSize(24, 24))
        self.btnOpenFile.setObjectName("btnOpenFile")
        self.btnLoadFile = QtWidgets.QPushButton(self.centralwidget)
        self.btnLoadFile.setGeometry(QtCore.QRect(750, 20, 31, 28))
        self.btnLoadFile.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/button/load"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnLoadFile.setIcon(icon3)
        self.btnLoadFile.setIconSize(QtCore.QSize(24, 24))
        self.btnLoadFile.setObjectName("btnLoadFile")
        self.barGraphAV = QtWidgets.QWidget(self.centralwidget)
        self.barGraphAV.setGeometry(QtCore.QRect(600, 380, 181, 141))
        self.barGraphAV.setAutoFillBackground(True)
        self.barGraphAV.setObjectName("barGraphAV")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "EAR Viewer"))
from pyqtgraph import GraphicsLayoutWidget, PlotWidget
import resource_rc
